### ISSUE TITLE
Background Color varies?

### ISSUE THREAD

**Issue by ktrinanm** [tomsik68/vim-crystallite#8]
![terminalill](https://cloud.githubusercontent.com/assets/16170034/22402128/4abfd774-e5a9-11e6-9b07-4ff004acccaa.png)

So when I turn on the Crystallite color, my background goes all wonky instead of being an even black color. I tried changing my terminal settings, but still ended up with the same issue. I'm not 100% familiar with vim color files, so I don't want to do any editing without being sure it will fix the issue. Please let me know if you have any ideas on how to solve this. 

I'm working off Linux Mint 18.1 in the terminal, with a dark desktop theme. It's a fairly new install so little has been changed from the default cinnamon settings.

**Comment by tomsik68** [comment]
Line numbers are explicitly set to black and comments are a little bit lighter than black so you can see them better. For everything else, Crystallite does not explicitly specify background color, so it uses background color of your terminal. 
I can tell your terminal has transparent background(I can see github formatting behind it :) ), so I'd say your background is transparent black color.
There are 2 ways to fix this: 
1.) You disable your terminal transparency
2.) I modify crystallite to set black background for everything

As crystallite is a dark scheme, it would make sense to use black backgrounds for everything, so I will go ahead with 2.) and modify the color scheme to use black background.

Thanks for reporting this!
